export interface Activity {
    id: string; // e.g., 'act_...'
    type?: 'activity' | 'food' | 'transport';
    title: string;
    location: string;
    description: string;
    cost_estimate: number;
    category: 'Food' | 'Sightseeing' | 'Adventure' | 'Relaxation' | 'Transport' | 'Nightlife' | 'Lodging';

    durationMinutes: number;
    time?: string;
    timeSlot?: {
        start: string;
        end: string;
    };
    coordinates?: { lat: number; lng: number };
    travelDistance?: number;
    travelTimeFromPrev?: number;
    status: 'planned' | 'completed' | 'skipped';
    imageGallery: string[]; // Google Photos URLs
    
    // Hydration Fields
    rating?: string;
    user_ratings_total?: number;
    contactNumber?: string;
    website?: string;
    openingHours?: string[];
    placeId?: string;

    metadata?: {
        isLocked?: boolean;
        source?: 'ai_generated' | 'user_added';
    };
    imageUrl?: string; 
    isDraft?: boolean; // UI state for manual adds
    isHydrating?: boolean; // UI state for AI suggestions
    
    // Ticketmaster / Event Fields
    isEvent?: boolean;
    bookingUrl?: string;
    price_note?: string;
    eventDate?: string;
}

export interface ActivitySkeleton {
    id: string;
    title: string;
    category: string;
    short_reason: string;
    // Rich fields generated by Phase 1 Gemini call — used directly in hydration (no second Gemini call)
    location?: string;
    description?: string;
    cost_estimate?: number;
    durationMinutes?: number;
    isSkeleton: true;

    // Ticketmaster / Event Fields
    isEvent?: boolean;
    bookingUrl?: string;
    price_note?: string;
    imageUrl?: string;
    start_date?: string; // ISO combined
}
